src/Entity/Document.php
<?php

namespace App\Entity;

use App\Repository\DocumentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DocumentRepository::class)
 */
class Document
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $intitule;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $etat_document;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $commentaire;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $date_depot;

    /**
     * @ORM\ManyToOne(targetEntity=Personne::class, cascade={"persist", "remove"})
     */
    private $depositaire;

    /**
     * @ORM\ManyToOne(targetEntity=Etudiant::class, inversedBy="documents")
     */
    private $etudiant;

    /**
     * @ORM\ManyToOne(targetEntity=TypeDocument::class, inversedBy="documents")
     */
    private $type_document;

    private $typeDocument2;

    /**
     * @ORM\ManyToOne(targetEntity=Tuteur::class, inversedBy="documents")
     */
    private $tuteur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): self
    {
        $this->intitule = $intitule;

        return $this;
    }

    public function getEtatDocument(): ?string
    {
        return $this->etat_document;
    }

    public function setEtatDocument(string $etat_document): self
    {
        $this->etat_document = $etat_document;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getDateDepot(): ?string
    {
        return $this->date_depot;
    }

    public function setDateDepot(?string $date_depot): self
    {
        $this->date_depot = $date_depot;

        return $this;
    }

    public function getDepositaire(): ?Personne
    {
        return $this->depositaire;
    }

    public function setDepositaire(?Personne $depositaire): self
    {
        $this->depositaire = $depositaire;

        return $this;
    }

    public function getEtudiant(): ?Etudiant
    {
        return $this->etudiant;
    }

    public function setEtudiant(?Etudiant $etudiant): self
    {
        $this->etudiant = $etudiant;

        return $this;
    }

    public function getTypeDocument(): ?TypeDocument
    {
        return $this->type_document;
    }

    public function setTypeDocument(?TypeDocument $type_document): self
    {
        $this->type_document = $type_document;

        return $this;
    }

    public function getTypeDocument2(): ?string
    {
        return $this->typeDocument2;
    }

    public function setTypeDocument2(string $typeDocument2): self
    {
        $this->typeDocument2 = $typeDocument2;

        return $this;
    }

    public function getTuteur(): ?Tuteur
    {
        return $this->tuteur;
    }

    public function setTuteur(?Tuteur $tuteur): self
    {
        $this->tuteur = $tuteur;

        return $this;
    }
}

src/Entity/Etudiant.php
<?php

namespace App\Entity;

use App\Repository\EtudiantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EtudiantRepository::class)
 */
class Etudiant
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type_contrat;

    /**
     * @ORM\ManyToOne(targetEntity=Formation::class)
     */
    private $formation;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $note_suivi;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $moyenne;

    /**
     * @ORM\OneToOne(targetEntity=Personne::class, cascade={"persist", "remove"})
     */
    private $personne;

    /**
     * @ORM\ManyToOne(targetEntity=Entreprise::class)
     */
    private $entreprise;

    /**
     * @ORM\ManyToOne(targetEntity=Planning::class, inversedBy="etudiants")
     */
    private $planning;

    /**
     * @ORM\OneToMany(targetEntity=Document::class, mappedBy="etudiant")
     */
    private $documents;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $note_oral;

    /**
     * @ORM\ManyToOne(targetEntity=Tuteur::class, inversedBy="etudiants")
     */
    private $tuteur;

    public function __construct()
    {
        $this->documents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeContrat(): ?string
    {
        return $this->type_contrat;
    }

    public function setTypeContrat(?string $type_contrat): self
    {
        $this->type_contrat = $type_contrat;

        return $this;
    }

    public function getFormation(): ?Formation
    {
        return $this->formation;
    }

    public function setFormation(Formation $formation): self
    {
        $this->formation = $formation;

        return $this;
    }

    public function getNoteSuivi(): ?int
    {
        return $this->note_suivi;
    }

    public function setNoteSuivi(?int $note_suivi): self
    {
        $this->note_suivi = $note_suivi;

        return $this;
    }

    public function getMoyenne(): ?float
    {
        return $this->moyenne;
    }

    public function setMoyenne(?float $moyenne): self
    {
        $this->moyenne = $moyenne;

        return $this;
    }

    public function getPersonne(): ?Personne
    {
        return $this->personne;
    }

    public function setPersonne(?Personne $personne): self
    {
        $this->personne = $personne;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getPlanning(): ?Planning
    {
        return $this->planning;
    }

    public function setPlanning(?Planning $planning): self
    {
        $this->planning = $planning;

        return $this;
    }

    public function getNoteOral(): ?float
    {
        return $this->note_oral;
    }

    public function setNoteOral(?float $note_oral): self
    {
        $this->note_oral = $note_oral;

        return $this;
    }

    /**
     * @return Collection|Document[]
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(Document $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents[] = $document;
            $document->setEtudiant($this);
        }

        return $this;
    }

    public function removeDocument(Document $document): self
    {
        if ($this->documents->removeElement($document)) {
            // set the owning side to null (unless already changed)
            if ($document->getEtudiant() === $this) {
                $document->setEtudiant(null);
            }
        }

        return $this;
    }

    public function getTuteur(): ?Tuteur
    {
        return $this->tuteur;
    }

    public function setTuteur(?Tuteur $tuteur): self
    {
        $this->tuteur = $tuteur;

        return $this;
    }
}

src/Entity/ResponsableUE.php
<?php

namespace App\Entity;

use App\Repository\ResponsableUERepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ResponsableUERepository::class)
 */
class ResponsableUE
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity=Personne::class, cascade={"persist", "remove"})
     */
    private $personne;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPersonne(): ?Personne
    {
        return $this->personne;
    }

    public function setPersonne(?Personne $personne): self
    {
        $this->personne = $personne;

        return $this;
    }
}

src/Entity/TypeDocument.php
<?php

namespace App\Entity;

use App\Repository\TypeDocumentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TypeDocumentRepository::class)
 */
class TypeDocument
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $intitule;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_limite;

    /**
     * @ORM\OneToMany(targetEntity=Document::class, mappedBy="type_document")
     */
    private $documents;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $delai_relance;

    public function __construct()
    {
        $this->documents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): self
    {
        $this->intitule = $intitule;

        return $this;
    }

    public function getDateLimite(): ?\DateTimeInterface
    {
        return $this->date_limite;
    }

    public function setDateLimite(\DateTimeInterface $date_limite): self
    {
        $this->date_limite = $date_limite;

        return $this;
    }

    public function getDelaiRelance(): ?float
    {
        return $this->delai_relance;
    }

    public function setDelaiRelance(?float $delai_relance): self
    {
        $this->delai_relance = $delai_relance;

        return $this;
    }

    /**
     * @return Collection|Document[]
     */
    public function getDocuments(): Collection
    {
        return $this->documents;
    }

    public function addDocument(Document $document): self
    {
        if (!$this->documents->contains($document)) {
            $this->documents[] = $document;
            $document->setTypeDocument($this);
        }

        return $this;
    }

    public function removeDocument(Document $document): self
    {
        if ($this->documents->removeElement($document)) {
            // set the owning side to null (unless already changed)
            if ($document->getTypeDocument() === $this) {
                $document->setTypeDocument(null);
            }
        }

        return $this;
    }

    public function __toString(): string {   
        return $this->getIntitule();
    }
}

src/Form/ResponsableUEType.php
<?php

namespace App\Form;

use App\Entity\ResponsableUE;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ResponsableUEType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('personne', EntityType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => ResponsableUE::class,
        ]);
    }
}

templates/responsableUE/accueil.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container">
        <a href="{{ path('tutor_list') }}">Liste des tuteurs universitaires</a> <br />
        <a href="{{ path('student_list') }}">Liste des étudiants et notes</a> <br />
        <a href="{{ path('setting') }}">Paramétrer les dates de rendu et délais de relance</a> <br />
        <a href="{{ path('tutor_assign') }}">Assignation des tuteurs</a> <br />
        <a href="{{ path('RUE_add_document') }}">Ajouter un document</a> <br />
        <a href="{{ path('RUE_documents') }}">Voir les documents</a> <br />
        <!--<a href="{{ path('RUE_see_feasibility_sheet') }}">Voir les fiches de faisabilité</a> <br />-->
        <!--<a href="{{ path('add_feasibility_sheet') }}">Importer une fiche de faisabilité</a>-->
    </div>
{% endblock %}

templates/responsableUE/accueil2.html.twig
<!DOCTYPE html>
<html> 
    <head>
        <meta charset="UTF-8">
        <link rel="icon" href="/images/favicon.ico" />
        <title>Responsable UE - Accueil</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
            <link href="{{ asset('css/custom_responsable.css') }}" type="text/css" rel="stylesheet">
        {% endblock %}
    </head>
    <body>
        <header>
            <nav class="nav">
                <h1>UPJV OGPP</h1>
                <h4>Déconnexion</h4>
            </nav>
        </header>
        <p>Liste des tuteurs universitaires<br \>
        Liste des étudiants et notes<br \>
        Paramétrer les dates de rendu et délais de relance<br \>
        Assignation des tuteurs<br \>
        Importer une fiche de faisabilité
        </p>
    </body>
</html>

templates/responsableUE/addComment.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="top_container">
        <h1>Document - {{ document.intitule }}</h1>
        {{ form_start(form) }}

        {{ form_label(form.commentaire, 'Commenter', {'label_attr': {'class': 'p'}} ) }}
        {{ form_widget(form.commentaire, {'attr': {'class': 'form-control', 'placeholder': 'Commentaire ...'} }) }}
        {{ form_errors(form.commentaire) }}

        <div class="form-group">
            {{ form_label(form.valider, 'Valider', {'label_attr': {'class': 'p'}} ) }}
            {{ form_widget(form.valider, {'attr': {'class': 'button3'}} ) }}
        </div>

        {{ form_end(form) }}
    </div>
    <div id="button" class="margin_top">
        <a class="button" href="{{ path('RUE_documents') }}" >Retour sur les documents</a>
    </div>
{% endblock %}

templates/responsableUE/addDocument.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="top_container">
        <h1>Importer un document</h1>
    </div>
    <div class="container">
        {{ form_start(formDocument) }}
        <div class="form-group">
            {{ form_label(formDocument.intitule, 'Sélectionner un fichier', {'label_attr': {'class': 'p'}} ) }}
            {{ form_widget(formDocument.intitule, {'attr': {'class': 'button_import'}} ) }}
        </div>

        <div class="top_container">
            {{ form_label(formDocument.typeDocument2, 'Type de document', {'label_attr': {'class': 'p'}} ) }}
            {{ form_widget(formDocument.typeDocument2, {'attr': {'class': 'custom-select'}} ) }}
        </div>

        <div class="top_container">
            {{ form_label(formDocument.etudiant, 'Étudiant', {'label_attr': {'class': 'p'}} ) }}
            {{ form_widget(formDocument.etudiant, {'attr': {'class': 'custom-select'}} ) }}
        </div>

        <div class="top_container" id="commentaire">
            {{ form_label(formDocument.commentaire, 'Commenter', {'label_attr': {'class': 'p'}} ) }}
            {{ form_widget(formDocument.commentaire, {'attr': {'class': 'form-control', 'placeholder': 'Commentaire ...'} }) }}
            {{ form_errors(formDocument.commentaire) }}
        </div>

        <script>
            document.getElementById("commentaire").style.display = 'none';
        </script>
        
        <div class="form-group">
            {{ form_label(formDocument.valider, 'Valider', {'label_attr': {'class': 'p'}} ) }}
            {{ form_widget(formDocument.valider, {'attr': {'class': 'button3'}} ) }}
        </div>
        {{ form_end(formDocument) }}
    </div>
    <div id="button">
        <a class="button" href="{{ path('home_responsable_ue') }}" >Retourner au menu principal</a>
    </div>
{% endblock %}

templates/responsableUE/affectTutor.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="top_container">
        <h1>Étudiant - {{ etudiant.personne.prenom }} {{ etudiant.personne.nom }}</h1>
        {{ form_start(form) }}

        {{ form_label(form.tuteur, 'Choix tuteur', {'label_attr': {'class': 'p'}} ) }}
        {{ form_widget(form.tuteur, {'attr': {'class': 'form-control', 'placeholder': 'Sélection un tuteur ...'} }) }}
        {{ form_errors(form.tuteur) }}

        <div class="form-group">
            {{ form_label(form.valider, 'Affecter', {'label_attr': {'class': 'p'}} ) }}
            {{ form_widget(form.valider, {'attr': {'class': 'button3'}} ) }}
        </div>

        {{ form_end(form) }}
    </div>
    <div id="button" class="margin_top">
        <a class="button" href="{{ path('tutor_assign') }}" >Retour sur les étudiants</a>
    </div>
{% endblock %}

templates/responsableUE/assignTutor.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container">
        <h1>Assignation des tuteurs</h1>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Étudiants</th>
                    <th scope="col">Entreprise</th>
                    <th scope="col">Localité</th>
                    <th scope="col">Tuteur</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for etudiant in etudiants %}
                <tr>
                    <th scope="row"></th>
                    <td>{{ etudiant.personne.prenom }} {{ etudiant.personne.nom }}</td>
                    <td>{{ etudiant.entreprise.nom }}</td>
                    <td>{{ etudiant.entreprise.localite }}</td>
                    <td>{{ etudiant.tuteur.personne.nom }} {{ etudiant.tuteur.personne.prenom }}</td>
                    <td>
                        <a class="navbar-brand" href="{{ path('tutor_affect', { 'id': etudiant.id }) }}">
                            <img src="/images/add.png" alt="icon ajouter" id="icon_add" class="icon_click">
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div id="button" class="margin_top">
        <a class="button" href="{{ path('home_responsable_ue') }}" >Retourner au menu principal</a>
    </div>
{% endblock %}

templates/responsableUE/commentTutor.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="top_container">
        <h1>Tuteur - {{ tuteur.personne.prenom }} {{ tuteur.personne.nom }}</h1>
        {{ form_start(form) }}

        {{ form_label(form.commentaire, 'Commentaire', {'label_attr': {'class': 'p'}} ) }}
        {{ form_widget(form.commentaire, {'attr': {'class': 'form-control'} }) }}
        {{ form_errors(form.commentaire) }}

        <div class="form-group">
            {{ form_label(form.valider, 'Valider', {'label_attr': {'class': 'p'}} ) }}
            {{ form_widget(form.valider, {'attr': {'class': 'button3'}} ) }}
        </div>

        {{ form_end(form) }}
    </div>
    <div id="button" class="margin_top">
        <a class="button" href="{{ path('tutor_list') }}" >Retour sur les tuteurs</a>
    </div>
{% endblock %}

templates/responsableUE/documents.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="top_container">
        <h1>Documents</h1>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Type document</th>
                    <th scope="col">Intitule</th>
                    <th scope="col">État document</th>
                    <th scope="col" colspan="4">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for document in documents %}
                <tr>
                    <th scope="row"></th>
                    <td>{{ document.typeDocument.intitule }}</td>
                    <td>{{ document.intitule }}</td>
                    <td>{{ document.etatDocument }}</td>
                    <td>
                        <a class="navbar-brand" href="{{ path('RUE_admit_comment', { 'id': document.id }) }}">
                            <img src="/images/check.png" alt="icon valider" id="icon_check" class="icon_click">
                        </a>
                    </td>
                    <td>
                        <a class="navbar-brand" href="{{ path('RUE_add_comment', { 'id': document.id }) }}">
                            <img src="/images/edit.png" alt="icon commenter" id="icon_edit" class="icon_click">
                        </a>
                    </td>
                    <td>
                        <a class="navbar-brand" href="{{ path('RUE_refuse_comment', { 'id': document.id }) }}">
                            <img src="/images/refuse.png" alt="icon refuser" id="icon_refuse" class="icon_click">
                        </a>
                    </td>
                    <td>
                        <a class="navbar-brand" href="{{ path('RUE_download', { 'id': document.id }) }}">
                            <img src="/images/download.png" alt="icon télécharger" id="icon_download" class="icon_click">
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <div id="button" class="margin_top">
        <a class="button" href="{{ path('home_responsable_ue') }}" >Retourner au menu principal</a>
    </div>
{% endblock %}

templates/responsableUE/editSetting.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="top_container">
        <h1>Type Document - {{ typeDocument.intitule }}</h1>
        {{ form_start(form) }}

        {{ form_label(form.dateLimite, 'Date Limite', {'label_attr': {'class': 'p'}} ) }}
        {{ form_widget(form.dateLimite, {'attr': {'class': 'form-control'} }) }}
        {{ form_errors(form.dateLimite) }}

        {{ form_label(form.delaiRelance, 'Delai de relance', {'label_attr': {'class': 'p'}} ) }}
        {{ form_widget(form.delaiRelance, {'attr': {'class': 'form-control'} }) }}
        {{ form_errors(form.delaiRelance) }}

        <div class="form-group">
            {{ form_label(form.valider, 'Valider', {'label_attr': {'class': 'p'}} ) }}
            {{ form_widget(form.valider, {'attr': {'class': 'button3'}} ) }}
        </div>

        {{ form_end(form) }}
    </div>
    <div id="button" class="margin_top">
        <a class="button" href="{{ path('setting') }}" >Retour sur les types de document</a>
    </div>
{% endblock %}

templates/responsableUE/feasibility.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container">
        <h1>Voir les fiches de faisabilités</h1>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Étudiants</th>
                    <th scope="col">Fiche de faisabilité</th>
                    <th scope="col">État</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for etudiant in etudiants %}
                <tr>
                    <th scope="row"></th>
                    <td>{{ etudiant.personne.nom }} {{ etudiant.personne.prenom }}</td>
                    <td>_document_.pdf</td>
                    <td>état</td>
                    <!--<td>Icon valider et refuser</td>-->
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div id="button">
        <a class="button" href="{{ path('home_responsable_ue') }}" >Retourner au menu principal</a>
    </div>
{% endblock %}

templates/responsableUE/setting.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="top_container">
        <h1>Paramétrer les dates de rendu et délais de relance</h1>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Intitulé</th>
                    <th scope="col">Date de rendu</th>
                    <th scope="col">Délai de relance</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for typeDocument in typeDocuments %}
                <tr>
                    <th scope="row"></th>
                    <td>{{ typeDocument.intitule }}</td>
                    <td>{{ typeDocument.dateLimite |date('Y-m-d') }}</td>
                    <td>{{ typeDocument.delaiRelance }}</td>
                    <td>
                        <a class="navbar-brand" href="{{ path('RUE_setting', { 'id': typeDocument.id }) }}">
                            <img src="/images/edit.png" alt="icon parametrer" id="icon_edit" class="icon_click">
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div id="button" class="group_button">
        <a class="button" href="{{ path('home_responsable_ue') }}" >Retourner au menu principal</a>
    </div>
{% endblock %}

templates/responsableUE/students.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container">
        <h1>Notes des étudiants</h1>
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Étudiants</th>
                    <th scope="col">Note Suivi</th>
                    <th scope="col">Note Oral</th>
                    <th scope="col">Note Finale</th>
                </tr>
            </thead>
            <tbody>
                {% for etudiant in etudiants %}
                <tr>
                    <th scope="row"></th>
                    <td>{{ etudiant.personne.nom }} {{ etudiant.personne.prenom }}</td>
                    <td>{{ etudiant.noteSuivi }}</td>
                    <td>{{ etudiant.noteOral }}</td>
                    <td>{{ etudiant.moyenne }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div id="button">
        <a class="button" href="{{ path('home_responsable_ue') }}" >Retourner au menu principal</a>
    </div>
{% endblock %}

templates/responsableUE/tutors.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="container">
        <h1>Listes des tuteurs</h1>

        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Enseignant</th>
                    <th scope="col">Commentaire</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for tuteur in tuteurs %}
                <tr>
                    <th scope="row"></th>
                    <td>{{ tuteur.personne.nom }} {{ tuteur.personne.prenom }}</td>
                    <td>{{ tuteur.commentaire }}</td>
                    <td>
                        <a class="navbar-brand" href="{{ path('tutor_comment', { 'id': tuteur.id }) }}">
                            <img src="/images/edit.png" alt="icon commenter" id="icon_edit" class="icon_click">
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div id="button">
        <a class="button" href="{{ path('home_responsable_ue') }}" >Retourner au menu principal</a>
    </div>
{% endblock %}